Document: opennhrp
Title: Debian opennhrp Manual
Author: <insert document author here>
Abstract: This manual describes what opennhrp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opennhrp/opennhrp.sgml.gz

Format: postscript
Files: /usr/share/doc/opennhrp/opennhrp.ps.gz

Format: text
Files: /usr/share/doc/opennhrp/opennhrp.text.gz

Format: HTML
Index: /usr/share/doc/opennhrp/html/index.html
Files: /usr/share/doc/opennhrp/html/*.html
